### ISSUE TITLE
4.5.0国服解锁不了

### ISSUE THREAD

**Issue by wangwenx190** [xiaonian233/genshin-fps-unlock#12]
我fork了你的仓库，做了些改造（核心逻辑没动），发现外服OSRel版本可以正常解锁，国服CNRel版本总是找不到UserAssembly.dll的内存地址

**Comment by wangwenx190** [comment]
https://github.com/wangwenx190/anime-game-fps-unlocker-cpp

**Comment by wangwenx190** [comment]
@xiaonian233  直接关了是什么意思？

**Comment by xiaonian233** [comment]
> @xiaonian233 直接关了是什么意思？

https://github.com/xiaonian233/genshin-fps-unlock/issues/9#issuecomment-1996235963

**Comment by wangwenx190** [comment]
> > @xiaonian233 直接关了是什么意思？
> 
> [#9 (comment)](https://github.com/xiaonian233/genshin-fps-unlock/issues/9#issuecomment-1996235963)

“我目前正在完成新版本，等新版本完成的时候会一起提交”，这都5月了，新版本还没提交吗？而且看你README的截图里明明4.6.0都支持了？

**Comment by xiaonian233** [comment]
新版本肯定是重构啊，没提交就是没做好么。特征没变化，旧版也能用。
