### ISSUE TITLE
4.6解锁不了，最高只能到60帧

### ISSUE THREAD

**Issue by Ju-Wikun** [xiaonian233/genshin-fps-unlock#14]

**Comment by xiaonian233** [comment]
有别的提示吗？下的是什么版本，是最小化的吗？我本地测试没有复现你的情况，如果没有其它信息我很难确定

**Comment by Ju-Wikun** [comment]
> 有别的提示吗？下的是什么版本，是最小化的吗？我本地测试没有复现你的情况，如果没有其它信息我很难确定

是最小化的版本，我是开窗口玩的游戏，帧率显示最高是60，我的电脑最高显示到120帧

**Comment by xiaonian233** [comment]
试试另外个版本看看控制台有没有什么错误信息输出

**Comment by Ju-Wikun** [comment]
![原神 2024_5_14 14_34_48](https://github.com/xiaonian233/genshin-fps-unlock/assets/169358635/8fd0aeb3-4eeb-4743-973c-7f5ca0877686)
> 试试另外个版本看看控制台有没有什么错误信息输出
正常运行没有错误信息，但解锁不了帧率

**Comment by xiaonian233** [comment]
> ![原神 2024_5_14 14_34_48](https://private-user-images.githubusercontent.com/169358635/330305434-8fd0aeb3-4eeb-4743-973c-7f5ca0877686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODQxNTQsIm5iZiI6MTcxNTY4Mzg1NCwicGF0aCI6Ii8xNjkzNTg2MzUvMzMwMzA1NDM0LThmZDBhZWIzLTRlZWItNDc0My05NzNjLTdmNWNhMDg3NzY4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxMDUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjVmMjZmYTVmYmJlYjk4MjVhY2M5MzFkNzZiZmIyYTYyMjU3ZmNmMTZkNTlkNWU1NjhiOWNiZGM4YTY0ZjRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UsmrJ5S8EQdj5u6zfOQwejvQP0JcGL47j9OTsZOvogQ)
> 
> > 试试另外个版本看看控制台有没有什么错误信息输出
> > 正常运行没有错误信息，但解锁不了帧率

看起来没有什么问题的样子，试试
https://github.com/34736384/genshin-fps-unlock
这个大佬的吧

**Comment by Ju-Wikun** [comment]
> > ![原神 2024_5_14 14_34_48](https://private-user-images.githubusercontent.com/169358635/330305434-8fd0aeb3-4eeb-4743-973c-7f5ca0877686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODQxNTQsIm5iZiI6MTcxNTY4Mzg1NCwicGF0aCI6Ii8xNjkzNTg2MzUvMzMwMzA1NDM0LThmZDBhZWIzLTRlZWItNDc0My05NzNjLTdmNWNhMDg3NzY4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxMDUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjVmMjZmYTVmYmJlYjk4MjVhY2M5MzFkNzZiZmIyYTYyMjU3ZmNmMTZkNTlkNWU1NjhiOWNiZGM4YTY0ZjRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UsmrJ5S8EQdj5u6zfOQwejvQP0JcGL47j9OTsZOvogQ)
> > > 试试另外个版本看看控制台有没有什么错误信息输出
> > > 正常运行没有错误信息，但解锁不了帧率
> 
> 看起来没有什么问题的样子，我这边也没办法复现，试试 https://github.com/34736384/genshin-fps-unlock 这个大佬的吧

可以了，感谢
