### ISSUE TITLE
4.7版本失效

### ISSUE THREAD

**Issue by bfloat16** [xiaonian233/genshin-fps-unlock#15]
![image](https://github.com/xiaonian233/genshin-fps-unlock/assets/38366253/f3e957b9-d656-4ece-a1c5-9f6c864d9f33)

**Comment by cyber114514** [comment]
+1，期待大佬更新

**Comment by xiaonian233** [comment]
已经收到了，这两天我看看

**Comment by sanxiu-snowfield** [comment]
byd 米哈游不干正事禁这个是干什么了！习惯一百多整帧数现在好难受

**Comment by Bo-He-J** [comment]
---------------------------
Error
---------------------------
ReadProcessMemory failed with code: 299

仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。


---------------------------
确定   
---------------------------
报错：（

**Comment by cyber114514** [comment]
我这边的症状是显示出pid过后读内存直接闪退，然后游戏本体启动了

**Comment by bfloat16** [comment]
> byd 米哈游不干正事禁这个是干什么了！习惯一百多整帧数现在好难受

应该是改了特征了吧，米哈游的操作正常（

**Comment by xiaonian233** [comment]
> > byd 米哈游不干正事禁这个是干什么了！习惯一百多整帧数现在好难受
> 
> 应该是改了特征了吧，米哈游的操作正常（

不是的，可以先用其它人的解锁。

**Comment by xiaonian233** [comment]
新版已经更新了，隐藏窗口版得等个一两天

**Comment by sanxiu-snowfield** [comment]
> 新版已经更新了，隐藏窗口版得等个一两天 [4.7](https://github.com/xiaonian233/genshin-fps-unlock/releases/tag/4.7)

好耶
