### ISSUE TITLE
[Version 4.7] FPS Unlocker (Hide Window version) no longer works

### ISSUE THREAD

**Issue by Boyishdude** [xiaonian233/genshin-fps-unlock#16]
It was working fine these past couple of days after the 4.7 patch released, but today it just stopped working, as it **no longer uncaps the framerate to 144 for me like it's supposed to**. I would provide the error info, but I use the Hide Window variant (because I record the game with Shadowplay; I don't want to accidentally record the FPS Unlock program instead) so I'm unable to. Is anyone else also having this issue? It's entirely possible that this bug also applies to the version that doesn't hide the window, but I haven't checked.

I apologize if this is hard to read, especially if Google Translate was used. I'm an English speaker, so I don't speak either version of Chinese.

**Comment by xiaonian233** [comment]
I have learned about the relevant issue and am currently trying to resolve it. Thank you for your attention to this project.

**Comment by Boyishdude** [comment]
No worries. I really like your program, so when it doesn't work properly, it naturally bothers me, haha.

This is somewhat related to this topic **:** if you want my thoughts on the shift in focus the last version of your program had, I think the idea of never having to update this program _is_ just theory. In practice, I believe the developers regularly changing the code of the game with major and small updates means that something in the game will inevitably brick your program. It's probably best to keep an eye on whether or not your program is working as intended in each patch, and if not, make the necessary changes as required.

**Comment by xiaonian233** [comment]
Normal version has been updated, Hide version is to update soon.
