### ISSUE TITLE
在b服里，会出现读取不到程序内存的情况。

### ISSUE THREAD

**Issue by qweretsd** [xiaonian233/genshin-fps-unlock#18]
我这里的情况是，在进入游戏，登录账号之前的fps都可以读到解锁的帧率。
界面切换之后就一直锁60，尝试切副本也无法重置。
但有时运气好能成功进入解锁帧率的大世界，虽然在进入副本时就会锁60.
试了一下官服，似乎没有出现这个问题。
有一个很明显的地方就是账号登录在加载大世界的时候，原神主程序会最小化，切换到别的程序后面。

**Comment by xiaonian233** [comment]
试试隐藏窗口的版本看看

**Comment by qweretsd** [comment]
> 试试隐藏窗口的版本看看

没有用，如果运气好第一次进到大世界的时候能解锁。但是重置场景之后一样会锁60。
说起来，昨天之前用了一两天都是可以像官服一样用的，不知道为什么昨天之后就陷入锁60了。

**Comment by xiaonian233** [comment]
> > 试试隐藏窗口的版本看看
> 
> 没有用，如果运气好第一次进到大世界的时候能解锁。但是重置场景之后一样会锁60。 说起来，昨天之前用了一两天都是可以像官服一样用的，不知道为什么昨天之后就陷入锁60了。

还是官服正常，B服有问题是吧？

**Comment by winTEuser** [comment]
试试关了垂直同步

**Comment by qweretsd** [comment]
> 试试关了垂直同步

我垂直同步是全局的，游戏设置里一直是关着的。官服那边也是这样设置。

**Comment by qweretsd** [comment]
> > > 试试隐藏窗口的版本看看
> > 
> > 
> > 没有用，如果运气好第一次进到大世界的时候能解锁。但是重置场景之后一样会锁60。 说起来，昨天之前用了一两天都是可以像官服一样用的，不知道为什么昨天之后就陷入锁60了。
> 
> 还是官服正常，B服有问题是吧？

是

**Comment by xiaonian233** [comment]
我下载个B服看看啥情况

**Comment by qweretsd** [comment]
> 我下载个B服看看啥情况

有官服的话，只需要下载一个转换器就可以了。

**Comment by winTEuser** [comment]
有报错截图之类吗

**Comment by qweretsd** [comment]
> 截图之类吗，还有设备类型

他没有报错啊。
设备是win10,5800h+3060。我不知道怎么贴更详细的，因为程序里也没有抓取日志可以让我贴。

**Comment by xiaonian233** [comment]
> > 截图之类吗，还有设备类型
> 
> 他没有报错啊。 设备是win10,5800h+3060。我不知道怎么贴更详细的，因为程序里也没有抓取日志可以让我贴。

全屏和窗口化看看有没有不一样的表现

**Comment by winTEuser** [comment]
拿我的仓库里的试试看看，看看有没有错误码

**Comment by qweretsd** [comment]
> > > 截图之类吗，还有设备类型
> > 
> > 
> > 他没有报错啊。 设备是win10,5800h+3060。我不知道怎么贴更详细的，因为程序里也没有抓取日志可以让我贴。
> 
> 全屏和窗口化看看有没有不一样的表现

没有区别吧。我感觉是破解程序找不到原神程序了，因为几个情况很明显，一是进入游戏时会原神程序最前失焦，被切换到虚空，这样就肯定只有60帧，有时能保持最前的状态载入，就能破解限制。然后就是像常见的单独关闭了破解程序之后切换场景会锁60帧这样的情况。

**Comment by qweretsd** [comment]
> 拿我的仓库里的试试看看，看看有没有错误码

Read Fps Fail! Error_code: 0x5
这样吗？

**Comment by qweretsd** [comment]
Read Fps Fail! Error_code: 0x5
Game Terminated !
实际上游戏还是开着的。
我也切到官服试了一下，没有这个问题。

**Comment by winTEuser** [comment]
可能驱动不一样？，看看你游戏文件夹下的hoyoKprotect日期

**Comment by winTEuser** [comment]
不一样，官服4.7签的是5月9号

**Comment by winTEuser** [comment]
那就启动前先把驱动拖出去，启动完成后再拉回去试试

**Comment by qweretsd** [comment]
> 那就启动前先把驱动拖出去，启动完成后再拉回去试试

我把kprotect挪到原神的上一层文件之后以为进不去游戏呢。
没想到不仅官服能正常开，B服也能正常解锁，切场景也没有锁60的问题了。

**Comment by winTEuser** [comment]
我这边复现不了，哪几个场景切换会出问题

**Comment by xiaonian233** [comment]
> > 那就启动前先把驱动拖出去，启动完成后再拉回去试试
> 
> 我把kprotect挪到原神的上一层文件之后以为进不去游戏呢。 没想到不仅官服能正常开，B服也能正常解锁，切场景也没有锁60的问题了。

你把新kprotect上传一下

**Comment by qweretsd** [comment]
> 我这边复现不了，哪几个场景切换会出问题



> > > 那就启动前先把驱动拖出去，启动完成后再拉回去试试
> > 
> > 
> > 我把kprotect挪到原神的上一层文件之后以为进不去游戏呢。 没想到不仅官服能正常开，B服也能正常解锁，切场景也没有锁60的问题了。
> 
> 你把新kprotect上传一下

可是他没有新的kprotect，我没拖回去D:\Genshin Impact\Genshin Impact Game，他在D:\Genshin Impact一样开。看修改日期，也没有变过。

**Comment by qweretsd** [comment]
> 我这边复现不了，哪几个场景切换会出问题

之前是重新载入场景的地方都会出现锁60的情况，比如进入尘歌壶，比如天赋，武器，圣遗物本。任务场景副本，周本这类单独的场景。

**Comment by xiaonian233** [comment]
> 无法复现

怀疑是老米灰度新驱动

**Comment by winTEuser** [comment]
> > 无法复现
> 
> 怀疑是老米灰度新驱动

不好说，一般保护逻辑写好在pbase里的，一般不会热更新，毕竟动内核还是有风险的

**Comment by qweretsd** [comment]
> > > 无法复现
> > 
> > 
> > 怀疑是老米灰度新驱动
> 
> 不好说，一般保护逻辑写好在pbase里的，一般不会热更新，毕竟动内核还是有风险的

我之前是用

[genshin-fps-unlock](https://github.com/34736384/genshin-fps-unlock)
时出现的问题，然后当时试了现在这个也是有这种问题。
在那边反馈，那边也有人跟回复说有这个问题，可能是b服偶发情况。

**Comment by xiaonian233** [comment]
> 我之后写个自动打补丁解锁帧率的吧

我搞了一套注入的方案，但是不敢试，怕老米封

**Comment by winTEuser** [comment]
> > 我之后写个自动打补丁解锁帧率的吧
> 
> 我搞了一套注入的方案，但是不敢试，怕老米封

给unityplayer打补丁就行了，不需要注入这么麻烦

**Comment by QuAnnan2019** [comment]
同b服，遇到了变换场景后，帧率锁60的情况。
![12](https://github.com/xiaonian233/genshin-fps-unlock/assets/96817118/beca5069-2744-4e33-bb16-9e15534d4e89)
![13](https://github.com/xiaonian233/genshin-fps-unlock/assets/96817118/450e833b-2a8f-429d-b1de-d11103d04047)
如果后续有了良好的解决方案，请回复我，谢谢。

**Comment by winTEuser** [comment]
我新建了个仓库放我的改版，可以参考一下源码

**Comment by QuAnnan2019** [comment]
> 我新建了个仓库放我的改版，可以参考一下源码

问题解决了，谢谢。
