### ISSUE TITLE
进入副本后锁60帧

### ISSUE THREAD

**Issue by piglaughcrazy** [xiaonian233/genshin-fps-unlock#19]
问题如题，在大世界中可以成功解锁，但进入副本后解锁失败了，重新锁回60帧了，并且退出副本在大世界中也锁60帧

**Comment by xiaonian233** [comment]
是官服还是B服呢？

**Comment by piglaughcrazy** [comment]
> 是官服还是B服呢？

大大您好，是B服

**Comment by xiaonian233** [comment]
> > 是官服还是B服呢？
> 
> 大大您好，是B服

参考置顶issue，将原神文件夹内的HoYoKProtect.sys先拖走，然后启动游戏后，再拖回来试试

**Comment by piglaughcrazy** [comment]
> > > 是官服还是B服呢？
> > 
> > 
> > 大大您好，是B服
> 
> 参考置顶issue，将原神文件夹内的HoYoKProtect.sys先拖走，然后启动游戏后，再拖回来试试

可以了！大佬强！请问以后启动游戏还需要重复这个步骤吗

**Comment by xiaonian233** [comment]
> > > > 是官服还是B服呢？
> > > 
> > > 
> > > 大大您好，是B服
> > 
> > 
> > 参考置顶issue，将原神文件夹内的HoYoKProtect.sys先拖走，然后启动游戏后，再拖回来试试
> 
> 可以了！大佬强！请问以后启动游戏还需要重复这个步骤吗

暂时吧，目前还没有想到更好的方案。后续如果有新方案会第一时间更新

**Comment by piglaughcrazy** [comment]
> > > 是官服还是B服呢？
> > 
> > 
> > 大大您好，是B服
> 
> 参考置顶issue，将原神文件夹内的HoYoKProtect.sys先拖走，然后启动游戏后，再拖回来试试

可以了！大佬强！请问以后启动游戏还需要重复这个步骤吗

**Comment by piglaughcrazy** [comment]
> > > > > 是官服还是B服呢？
> > > > 
> > > > 
> > > > 大大您好，是B服
> > > 
> > > 
> > > 参考置顶issue，将原神文件夹内的HoYoKProtect.sys先拖走，然后启动游戏后，再拖回来试试
> > 
> > 
> > 可以了！大佬强！请问以后启动游戏还需要重复这个步骤吗
> 
> 暂时吧，目前还没有想到更好的方案。后续如果有新方案会第一时间更新

好的，谢谢大佬

**Comment by xiaonian233** [comment]
> > > > > > 是官服还是B服呢？
> > > > > 
> > > > > 
> > > > > 大大您好，是B服
> > > > 
> > > > 
> > > > 参考置顶issue，将原神文件夹内的HoYoKProtect.sys先拖走，然后启动游戏后，再拖回来试试
> > > 
> > > 
> > > 可以了！大佬强！请问以后启动游戏还需要重复这个步骤吗
> > 
> > 
> > 暂时吧，目前还没有想到更好的方案。后续如果有新方案会第一时间更新
> 
> 好的，谢谢大佬

https://github.com/winTEuser/Genshin_StarRail_fps_unlocker/releases
尝试一下
