### ISSUE TITLE
希望可以适配无边框模式~

### ISSUE THREAD

**Issue by ranshiin35** [xiaonian233/genshin-fps-unlock#2]
您好，我是B站来的BV1Mh4y1w7zj非常感谢分享！视频已三连！
您发布的版本不适配无边框启动，我的无边框方式是跟影月月学的BV15d4y1k7c8，非常希望您可以加入这个功能~这样我就可以一块屏幕查攻略，另一块屏幕的原神不会退回桌面了~
![0b1d0bb3017ed3335821f688cdce7c3](https://github.com/xiaonian233/genshin-fps-unlock/assets/142257802/a84d9e15-1d69-4aee-a14e-f51f890522fc)

**Comment by xiaonian233** [comment]
收到，下来我会查看这个问题，我这边主要是在窗口化/全屏方式下，你这个建议我试试
