### ISSUE TITLE
4.7版本进入副本掉60帧

### ISSUE THREAD

**Issue by wym987** [xiaonian233/genshin-fps-unlock#20]
4.7版本进入副本掉60帧，目前不知道是下载量第一的大佬不知道还是他还没解决，本作者也没解决这个问题。

**Comment by xiaonian233** [comment]
也是B服吗？

**Comment by wym987** [comment]
> > 也是B服吗？
> 
> 官服也是，另外一个仓库的unlockfps_nc也是

对的，是官服，B服不清楚。

**Comment by xiaonian233** [comment]
尝试最新版本

**Comment by wym987** [comment]
> 尝试最新版本

好辣，谢谢大佬！

**Comment by xiaonian233** [comment]
正如我所说，可以给winTEuser老哥https://github.com/winTEuser/Genshin_StarRail_fps_unlocker/releases
点个star
