### ISSUE TITLE
官服，今天切换地图后帧率重回60帧

### ISSUE THREAD

**Issue by Wintering666** [xiaonian233/genshin-fps-unlock#21]
今天刚上一次号发现帧率很低，看了一下是60，重开原神之后回到了120，但是切换到层岩巨渊后又回到了60帧

**Comment by Wintering666** [comment]
重新试了一下，在进入游戏大门的界面还能锁120，但是点进去之后，加载完毕就又回到锁60帧了

**Comment by xiaonian233** [comment]
收到，我这几天看看

**Comment by xiaonian233** [comment]
尝试最新版本

**Comment by Wintering666** [comment]
> 尝试最新版本

谢谢大佬，但是新版发现新问题了，新版本可以突破60帧率了，但是帧数无法锁定。
![1719470200888](https://github.com/xiaonian233/genshin-fps-unlock/assets/107615755/ce1e2801-ca47-460e-a601-07641ee5a5c5)
![微信图片_20240627143602](https://github.com/xiaonian233/genshin-fps-unlock/assets/107615755/578395b1-47d8-4856-a98b-76c2fa6cd37c)

**Comment by winTEuser** [comment]
> > 尝试最新版本
> 
> 谢谢大佬，但是新版发现新问题了，新版本可以突破60帧率了，但是帧数无法锁定。 ![1719470200888](https://private-user-images.githubusercontent.com/107615755/343657539-ce1e2801-ca47-460e-a601-07641ee5a5c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODE4NTEsIm5iZiI6MTcxOTQ4MTU1MSwicGF0aCI6Ii8xMDc2MTU3NTUvMzQzNjU3NTM5LWNlMWUyODAxLWNhNDctNDYwZS1hNjAxLTA3NjQxZWU1YTVjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QwOTQ1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTJiNzMzMjE0Mjg2ZWE0NmU2MDBmMDQxODMxZDRlOTMxZmFiNDE4M2VmNzA2ZWE4ZTc4MzgwZDBhYjk1ZmRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FRHQfZbV_ZAadcL-hfKoEuVYffpYBRylTQVEUZKc21U) ![微信图片_20240627143602](https://private-user-images.githubusercontent.com/107615755/343657571-578395b1-47d8-4856-a98b-76c2fa6cd37c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODE4NTEsIm5iZiI6MTcxOTQ4MTU1MSwicGF0aCI6Ii8xMDc2MTU3NTUvMzQzNjU3NTcxLTU3ODM5NWIxLTQ3ZDgtNDg1Ni1hOThiLTc2YzJmYTZjZDM3Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QwOTQ1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTM5MmFhYWY0NjA0MWE3ZDVkNjEwYzM4YzFmZGZiMjdkNDJhNDg4MTA2ZGU3ZmJjNzM1M2IyMTgxOTdjNWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sE7alRDDKKrRindO9ChmInegwVhbMZYDbhjLnZrjJf8)

游戏内设置到45
