### ISSUE TITLE
4.8解锁帧率不能调整FPS

### ISSUE THREAD

**Issue by 200155ck** [xiaonian233/genshin-fps-unlock#26]
大佬，调整FPS功能失效了，调整为60 OFF还是处于高帧率状态。解锁帧率没问题，默认是解锁到无限制帧率的

**Comment by xiaonian233** [comment]
我这里测试正常诶，游戏内调45FPS档位是解锁器的帧率，60是无上限。再试试？

**Comment by 200155ck** [comment]
大佬，就是通过快捷键设置目标帧率，右ctrl+上下调节，例如我要调到80帧，实际却不是80帧，是100多帧。调到60帧率，实际还是100多帧

**Comment by xiaonian233** [comment]
正如详情页缩写，你需要在游戏内帧率设置[https://github.com/xiaonian233/genshin-fps-unlock#%E5%AF%B9%E5%B8%A7%E6%95%B0%E7%9A%84%E8%AF%B4%E6%98%8E](url)帧率调为45档，将和解锁器的帧率一致，如果为60档是无限制
