### ISSUE TITLE
4.8版本失效

### ISSUE THREAD

**Issue by Wintering666** [xiaonian233/genshin-fps-unlock#27]
又需要麻烦大佬了
![image](https://github.com/user-attachments/assets/85eb067a-0a9c-40f1-a4a4-477db97e8985)

**Comment by xiaonian233** [comment]
下最新版了吗？

**Comment by xiaonian233** [comment]
昨天更新的最新版，我这一切正常

**Comment by xiaonian233** [comment]
如果下载新版还有问题，重新打开这个issue
