### ISSUE TITLE
4.0水下游泳时会出现帧率不稳的情况

### ISSUE THREAD

**Issue by cyber114514** [xiaonian233/genshin-fps-unlock#3]
如题，实际帧率不稳幅度较大给人一抖一抖的感觉，上岸后远离水边后恢复。

**Comment by xiaonian233** [comment]
我检查检查吧，如果复现不了的话我可能也没办法解决了

**Comment by cyber114514** [comment]
可能是游戏引擎的问题，降低帧率上限之后好了很多

**Comment by xiaonian233** [comment]
有些场景会出现这个问题，原因暂时不明，就请降低上限使用吧，后续如果我有办法解决会及时更新~
