### ISSUE TITLE
如何更改游戏安装路径

### ISSUE THREAD

**Issue by rosystain** [xiaonian233/genshin-fps-unlock#4]
游戏安装目录变动后，工具提示”配置里的游戏路经改变了 - 开始重新配置“后闪退。
删掉原本的配置文件应该就能解决了但是找不到在哪里。

**Comment by xiaonian233** [comment]
配置文件是与工具同目录下的fps_config.ini文件
![image](https://github.com/xiaonian233/genshin-fps-unlock/assets/21072615/1a03da76-9737-4e0e-8f9b-aec7cf3ede0b)
如图所示
