### ISSUE TITLE
4.5代码变动

### ISSUE THREAD

**Issue by frankxu2004** [xiaonian233/genshin-fps-unlock#9]
感谢您的项目！我下载了最新release 中的exe，是可以使用的，但是我看代码本身没有什么修改，我用之前的源码编译后，无法找到UnityPlayer.dll 和UnityAssembly.dll 导致注入失败，想请问是否代码应有变动呢

**Comment by xiaonian233** [comment]
应该是模块的地址获取有问题的样子，如果着急的话你可以借鉴一下别的程序。我目前正在完成新版本，等新版本完成的时候会一起提交
